Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10
